### ISSUE TITLE
Return Delay Time API

### ISSUE THREAD

**Issue by grassjelly** [sylvaing19/DynamixelAX12#1]
Hi,

Thanks for working on this great library. I’ve been using it to control 12 Dynamixel 12A servos on a Teensy3.2 for a quadrupedal robot. Is there any way to control the Return Delay Time and what’s the default value sent to the servos? I saw you have a constant for this register but can’t find it on any of the classes (or maybe I missed it).

Just curious, what’s the fastest control rate you’ve reached so far?

**Comment by grassjelly** [comment]
Closing this. I added a function that writes to DYN_ADDRESS_RDT register to change the Return Delay Time. Thanks!

**Comment by sylvaing19** [comment]
Hi,
thanks for using this library !
The "Return delay time" is not a setting that will be changed very often, this is why there is no function specially written for setting it. The intended way of setting it is by calling the `write` function and using `DYN_ADDRESS_RDT` (defined in `Dynamixel.h`) for the register address.
Please note that this setting is stored in the EEPROM area of the AX12 and will remain after reboot. This is why the value is not set at startup by the library. It should only be configured once manually (by using a custom code, or the GUI in https://github.com/sylvaing19/OneWireInterface/tree/dev-gui ) but not at each startup.

The minimal value for the RDT depends on your µC, with a teensy 3 you can set it to 0 since the teensy is much much faster than the AVR  inside the AX12.

Don't hesitate to ask if you have other questions.

**Comment by grassjelly** [comment]
Thanks for pointing that out. Omitted the functions that I added. I didn't realise that there's a GUI to configure the servos. Thanks for the tip!

Btw, here's what I've been working on. Kudos to your library :) https://www.youtube.com/watch?v=EKcLNfUA8rc
